---
title: "Data Science Project Assignment"
date: "Report and Presentation due Monday, March 13"
author: "Proposal and Progress Report due Friday, Monday February 27"
output: 
  html_document: 
    theme: cerulean
    fig_height: 4
    fig_width: 9
    toc: true
    toc_float: true
    toc_depth: 2
---


```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
library(tidyverse)
```


# Overview

The final project for this class is a collaborative analysis of a dataset of your group's choosing. You will need to form a group of 3 or 4 to work together on this project. Thank you in advance for taking your involvement in the work of the group seriously and for doing your share.


For the purposes of this project, you will need to find "published"
data from online sources along the lines of what we've been seeing in the Dataset of the Day presentations. You can choose the data based on your interests or based on work in other courses or research projects. The goal of this project is for 
you to find a dataset that the entire group can be interested in and to demonstrate proficiency in the techniques we have learned in this class (and beyond, if you like). 

# Data

In order for you to have the greatest chance of success with this project it is important that 
you choose a manageable yet challenging dataset. This means that the data should be readily accessible and large enough that you can explore several meaningful questions. Rather than download a single tidy data set for analysis, I expect you will need to tidy and possibly combine multiple data sets, possibly from more than one source. You should try to ensure that the data are sufficiently complex and messy to allow you to demonstrate your proficiency using the topics explored so far and those to come in the weeks ahead (e.g., merging, handling strings, dates, mapping, and writing functions to streamline or simplify code). 

Once tidied, your dataset should have at least 200 
observations (maybe many more) and between 10 to 20 variables (exceptions can be made but speak with me 
first to get approval). Your dataset should include categorical variables, discrete numerical 
variables, and continuous numerical variables. A dataset with only categorical or only numerical variables will severely limit the kinds of analyses you can carry out.  

One example of an appropriate dataset would be the Ames housing data we have worked with. Such a dataset could be created by merging data from several sources, e.g, using a home sales site like Zillow.com or Trulia plus information about neighborhood, schools, etc. 

**All analyses must be done in RStudio.** If you are using a dataset that comes in a format that 
we haven't encountered in class (e.g., JSON, XML, etc.), make sure that you are able to load it
into RStudio as this can be challenging depending on the source. (I can point you to resources that might be helpful.)

**Reusing datasets from class:** Do not reuse datasets used in examples or homework in the
class or datasets featured in the text. One partial exception is that you may use the Bureau of Transportation website to create your own flight dataset similar to the data in the `nyfcflights13` package if you 
obtain data for a different origin city but you should ensure that your analysis is original.

**Scraping data** You may scrape data from a website only if permission is explicitly given by the website and only to the extent permitted.

# Components of the Project

## Project proposal and progress report

Due Monday, February 27, this is a two-page proposal and progress report written using R Markdown and describing:  
 
* Your data source(s)  

* The variables you plan to use, including variables you plan to generate from your raw data  

* Questions you plan to address  

* An outline of your final product and a description of data  visualizations 
you expect to make      

* A progress report describing what work has been completed and what work remains to be completed   

* All materials should be kept in your group's shared repository on GitHub.

    + Code snippets and documents may be stored in the home folder.  
    + Data files should be stored in a `data` folder within your repository.  


## Report

After providing the description of your dataset and research question in the 
introduction use the remainder of your write up to showcase how you have arrived at 
an answer / answers to your questions of interest using any techniques we have learned in this
class (and some beyond, if you're feeling adventurous). The goal is not to do an exhaustive 
data analysis, but rather to show that you are proficient at 
asking meaningful questions and answering them with results of data wrangling
and visualization, that you are proficient in using R, and that you are proficient at interpreting and presenting the results. Also pay attention to your presentation. Neatness, coherency, and clarity will count.

Your write up must also include a one to two page conclusion and discussion. 
This will involve a summary of what you have learned about your research 
question along with data-based arguments supporting your conclusions. Also 
critique your own methods and provide suggestions for improving your analysis. 
Issues pertaining to the reliability and validity of your data, and 
appropriateness of your procedures should be discussed here. A 
paragraph on what you would do differently if you were able to start over 
with the project or what you would do next if you were going to continue 
work on the project should also be included.

The project is very open ended. You should create some kind of compelling 
visualization(s) of this data in R. All work should be carried out in RStudio 
and should rely on the capabilities of the `tidyverse`  packages we learned in class (`tidyverse`) rather than on brute force base R programming. You do not need to visualize all
of the data at once. A few high quality 
visualizations will receive a much higher grade than a large number of poor quality 
visualizations.

Before you finalize your write up, make sure your chunks are turned off 
with `echo = FALSE`. See more on this in the tips section below.

You can add sections as you see fit to your report. Make sure 
you have a section called Introduction at the beginning and a section called 
Conclusion at the end. The rest is up to you!


## Presentation

Presentations will happen during the scheduled exam time for this course. They should be 15 minutes maximum and each team member should say something substantial.

You can use any software you like for your final presentation, including R Markdown
to create your slides. There isn't a specific limit to how many slides you can use, just a 
time limit (15 minutes total). Each team member should get a chance to speak during 
the presentation. Your presentation should not just be an account of everything you 
tried but should describe how you created your data and what you learned supported by a very limited number of useful visuals. 

## Deliverables

Your submission on GitHub should include:

* RMarkdown file (formatted to clearly present all of your code and results)  

* HTML file  

* Dataset(s) (in csv format, in a `/data` folder)  

* Presentation (if using Keynote/PowerPoint/Google Slides, export to PDF and put in your GitHub folder, in a `/presentation` folder)    



Style and format does count for this assignment, so please take the time to make 
sure everything looks good and your data and code are properly formatted.

# Tips

* You will need to figure out how best to work collaboratively on GitHub. Discuss in advance how you intend to work. Pull first and commit and push often. I will do my best to help if (Git) conflicts arise but cannot make any guarantees. By making frequent commits, you reduce the chance of losing valuable work. 

* Review the grading guidelines below and ask questions if any of the expectations are unclear.    

* Set aside time to work together on Teams or whatever works best for you.

* Code: In your write up your code should be hidden (`echo = FALSE`) so that your document is neat and easy to read. However your document should include all your code such that if I re-knit your Rmd file, I should be able to obtain the results you presented. **Exception:** If you want to highlight something specific about a piece of code, you are welcome to show that portion.    

* Teamwork: You are to complete the assignment as a team. All team members are expected 
to contribute equally to the completion of this assignment and group 
assessments will be given at its completion. Anyone judged to not have sufficiently 
contributed to the final product will have their grade penalized. While different 
teams members may have different backgrounds and abilities, it is the responsibility 
of every team member to understand how  all code,  visualizations and  analysis in
your work.   


**Team peer evaluation** You will be asked to fill out a survey where you 
rate the contribution and teamwork of each team member out of 10 points. You will 
additionally report a contribution percentage for each team member. Filling out the 
survey is a prerequisite for getting credit on the team member evaluation.
If you are suggesting that an individual did less than 20% of the work, please
provide some explanation. If any individual gets an average peer score 
indicating that they did less than 10% of the work, this person will receive 
half the grade of the rest of the group.   

Your project score will be based on the quality of your team’s final product and presentation.  A high quality Final Product will show your abilities to collect, organize, tidy, visualize and interpret data. It should show both careful work as well as creativity. Your report and presentation should tell a compelling story with excellent written descriptions and graphics.   

Late projects will not be accepted except in extraordinary situations.   

# Grading  

Total                          | 100 pts  
-------------------------------|--------  
Proposal                       | 20 pts  
Presentation                   | 25 pts  
Write up                       | 30 pts  
Classmates' scores             | 5 pts  
Team peer evaluation           | 10 pts  
RStudio GitHub folder completeness and  organization | 10 pts  




# Timeline  

Stage                                                   | Date
--------------------------------------------------------|--------
Proposal and progress report                            | Monday, February 27
Project work day                                        | Friday, February 24
Final report and presentation                           | Monday, March 13




<div class="footnote">
**Note**: No pie charts please!
</div>


<div class="footnote">
**Source**: Adapted from [Data Science in a Box](https://datasciencebox.org/) Project Assignment
</div>
